### PR TITLE
Bug fix : disable addon fix

### PR DESCRIPTION
**Pull request by hrithikwins**
In this as a part of Taco Tuesday we tested this bugfix and under Imaginer's guidance, we were able to fix this bug

To reproduce the bug before the bugfix, 
Go to preferences > addons > behaviour graph > uncheck on checkbox

### CODE REVIEW

**Review by keianhzo — APPROVED** [review]
Thanks @hrithikwins !

**Comment by keianhzo** [comment]
We still have some issues as we are now double unregistering components when Blender is closed but that can be addressed in another PR

**Comment by hrithikwins** [comment]
Yes, I confirmed this, when I open blender > enable > disable > again enable
it causes problems and pointed out it is due to the unregister not removing everything 🗡️

**Comment by hrithikwins** [comment]
Imaginer and I again in Taco Tuesday observed that this problem is caused only in Macs, I'm on a m2, and you are on intel, so it's something that the macos blender is causing
It's working perfecting fine on Imaginer's blender in linux


In utils.py changing this solved the bug but this may not the right way to solve this bug unless all of us agree on this 😆 
image

**Comment by hrithikwins** [comment]
The issue in commment stated above was resolved by @keianhzo 's future commits in master branch
 🗡️

**Pull request merged**
