### PR TITLE
Update nodespec.json to add the Change Hub node.

### PR DESCRIPTION
**Pull request by Exairnous**
Companion PR for https://github.com/mozilla/hubs/pull/6411

### CODE REVIEW

**Review by keianhzo — CHANGES_REQUESTED** [review]
The category for this should be "Misc" and ideally it should be after the `displayMessage` node at the bottom i of f this file. Otherwise it LGTM. Thanks!

**Comment by Exairnous** [comment]
I could update it here, but I got that from the nodespec generated by the Hubs client, so shouldn't it be changed there?  Otherwise, the next time someone goes to add a new node the changes to the category will get overwritten, or am I misunderstanding something?

**Comment by keianhzo** [comment]
Oh yep, the order might require some more reordering in the client. I can fix that later, I think updating the category is ok for now.

**Comment by keianhzo** [comment]
Yes, that's what needs to be changed and then the json should be overriden here

**Comment by Exairnous** [comment]
Okay.  Thanks.  I've added a PR to change it on the client side and updated this PR to match.
https://github.com/mozilla/hubs/pull/6438

**Pull request merged**
