### PR TITLE
Coordinate system migration support

### PR DESCRIPTION
**Pull request by keianhzo**
This PR makes all exported vectors to use the right coordinate system and also adds a migration stage to convert the values at scene load time.

### CODE REVIEW

**Review by Exairnous — CHANGES_REQUESTED** [review]
I think this looks pretty good, but there are a few things I noticed:
* Node groups can be brought along with objects when appended/linked so the version should be stored on the node group and it should be updated after the migration, just like we do for components.
* Only the selected parameter is migrated for events.  I think all the parameters that are of type Vector3 should be migrated.
* Links aren't switched from Y sockets to Z sockets and vice versa.  I understand that this is probably pretty tricky, but it does mean that a significant part of the graph won't get migrated and we'll be left with half migrated graphs that people will have to manually clean up.  So, not sure what should be done with this.

**Comment by keianhzo** [comment]
Yeah good call, actually the version should be stored in every object that can be migrated: scenes, objects and node trees. I've added that.

Eventually we should also migrate for appended/linked objects same as we do for components but I think for now is ok with leaving that outside and supporting it later as this is still an alpha and I don't expect a lot of people to be linking pre-existing files. Alphas are alphas for a reason and supporting that would require a considerable amount of work which can probably be better put in other areas.

Regarding links, as we are migrating the root non-linked sockets, that should make linked final sockets to receive the right values so I don't think we need to migrate links.

**Comment by Exairnous** [comment]
Thanks.

Yeah, I guess for now we don't support migration on append/link.  If we do want add-ons to be built off the main one though we should probably provide a hook for that, then it would be easy (we just register our migrate function and then it would get called at the appropriate time).

I'm not sure about migrating linked sockets yet.  Actually, the swapping doesn't seem to work for this.  See this example blend file for what I mean.

[BG_Swizzle_test_01.zip](https://github.com/MozillaReality/blender-gltf-behavior-graph/files/15245759/BG_Swizzle_test_01.zip)

**Comment by keianhzo** [comment]
Thanks for diving into that. Yes, that won't work in this migration. For that to work we would need to expose the gltf_yup setting to the BGs addon and swizzle in the client for those nodes. That would require quite some work and it will add quite some code just to cover this pre-alpha migration case. As I mentioned in the meetup the goal of this migration is to support pre-existing demo scenes and not so much to support content created with the pre-alpha versions so as long as the demo scenes work, we are good. 

Te nodes that I can see that could be affected by this would be:
- Vec3 To Float
- Vec3 Combine
- Float To vec3
- Separate Vec3
- Euler Combine
- Separate Euler

I haven't seen any of them used in the demo scenes but I'll test them all to make sure. I think unless there is anythign else I'll land this as it's cover the more general pre-alpha case for demo scenes.

**Comment by Exairnous** [comment]
You're welcome!  Just to clarify, aside from it not migrating, it's switching them on export either.  Looking at the exported glb file, it looks like it should just need the same treatment as the others, but I haven't looked into the export code to see.

**Comment by keianhzo** [comment]
I think we should be doing swizzling based on the gltf_yup flag on any data exported by the addon and then do swizzling on those nodes in the client that transform vec3/euler. I've added a graph export metadata that sets the exporter gltf_yup and that we can check on the client add-on to do the swizzling. I've also added swizzling for:
Te nodes that I can see that could be affected by this would be:
    Vec3 To Float
    Vec3 Combine
    Float To vec3
    Separate Vec3
    Euler Combine
    Separate Euler
But in the future we will need to be aware of this when adding any nodes that are transforming vec3/euler:
https://github.com/MozillaReality/hubs-behavior-graphs-addon/commit/1baba581cb27c4140d6cbd04768341a5e65774b9

**Comment by keianhzo** [comment]
Btw, regarding migration, as I mentioned in the meetup, the goal of this migration is to support pre-existing demo scenes and not so much to support content created with the pre-alpha versions and I haven't seen any demo scenes using the nodes mentioned in my previous message. I think I'm going to land this as it covers the more general pre-alpha cases.

**Pull request merged**
